<?php
/*
* Description: this doument create all the modals for all the speakers in the database.
* IMPORTANT: notice that the trigger is generated by using the words speaker-$id
* Take a look at the code and be carefull to not change the structure of the attibute data-bs-target="#speaker-$id"
*/

$avatar = !empty($args[2]['url']) ? $args[2]['url'] : get_template_directory_uri() . "/img/avatar.png";
?>
<style>
    .modal-body .ratio-1x1 {
        width: 50%;
        margin: 0 auto;
    }

    .modal-content {
        box-shadow: 0px 4px 8px #00000029;
        border-radius: 10px;
    }

    .modal-header {
        padding: 0;
        padding-right: 20px;
        padding-top: 15px;
        border: none;
    }

    .ratio-1x1 img,
    .ratio-1x1 svg {
        object-fit: cover;
    }
    
    .ratio-1x1 {
    --bs-aspect-ratio: 100%;
}
.ratio {
    position: relative;
    width: 100%;
}
.ratio::before {
    display: block;
    padding-top: var(--bs-aspect-ratio);
    content: "";
}
.ratio>* {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

    .speaker .speaker-name,
    .speaker-modal-information .speaker-name {
        font-size: 22px;
    }

    .speaker .speaker-information,
    .modal-body .speaker-information {
        font-size: 14px;
    }

    .speaker-modal-information {
        border-left: solid 4px <?= $args[0] ?>;
        padding-left: 15px;
    }

    .modal-header .modal-header-close {
        background-color: <?= $args[0] ?>;
        color: <?= $args[1] ?>;
        border: transparent;
        height: 2rem;
        width: 2rem;
        text-align: center;
    }

    /*
	/* Bootstrap Media Query
	*/

    /* X-Small devices (portrait phones, less than 576px)
			No media query for `xs` since this is the default in Bootstrap */

    /* Small devices (landscape phones, 576px and up) */
    @media (min-width: 576px) {}

    /* Medium devices (tablets, 768px and up) */
    @media (min-width: 768px) {}

    /* Large devices (desktops, 992px and up) */
    @media (min-width: 992px) {
        .modal-body .ratio-1x1 {
            width: 40%;
        }
    }

    /* X-Large devices (large desktops, 1200px and up) */
    @media (min-width: 1200px) {
        .modal-body {
            padding-left: 3rem;
            padding-right: 3rem;
            padding-bottom: 1.5rem;
        }
    }

    /* XX-Large devices (larger desktops, 1400px and up) */
    @media (min-width: 1400px) {}
</style>
<?php

//creating the modals
$speakers = synclogic_get_all_speakers();
$modals = "";
foreach ($speakers as $speaker) {
    $id = $speaker->speaker_id;
    $image = $speaker->image_profile;
    $name = $speaker->speaker_name;
    $last_name = $speaker->speaker_family_name;
    $company = $speaker->company;
    $job_title = $speaker->job_title;
    $biography =  $speaker->biography;
    if ($biography == "<p>0</p>" || empty($biography)) {
        $biography = "";
    }

    if (empty($image) || (substr($image, -2) == "/0")) {
        $image = $avatar;
    }

    $modals .= <<<MODALS
            <div class="modal fade" id="speaker-$id" data-keyboard="false" tabindex="-1" aria-labelledby="speaker-$id-Label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content">
                        <div class="modal-header justify-content-end">
                            <button type="button" class="modal-header-close rounded-circle" data-dismiss="modal" aria-label="Close"><span>X</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="ratio ratio-1x1 mb-3">
                                <img loading="lazy" class="img-fluid d-block mx-auto rounded-circle" src="$image">
                            </div>
                            <div class="text-start row justify-content-center">
                                <div class="col-6 col-md-5 speaker-modal-information">
                                    <div class="speaker-name">$name $last_name</div>
                                    <div class="speaker-information">
                                        <div>$company</div>
                                        <div>$job_title</div>
                                    </div>
                                </div>
                            </div>
                            <div class="pt-4 text-start speaker-information">$biography</div>
                        </div>
                    </div>
                </div>
            </div>
    MODALS;
}

echo $modals;
